### ISSUE TITLE
음식점 데이터 API 구현

### ISSUE THREAD

**Issue by tlsdhsdb** [SWIDX/Eats-Mate-Backend#7]
- [x] 음식점 데이터 MariaDB, JPA 연동 및 불러오기
- [x] 검색용 음식점 데이터 CRUD API 구현 
- [ ] ~~음식점 위치 데이터 Point 데이터 JPA로 불러오기 (hibernate-spatial)~~

**Comment by tlsdhsdb** [comment]
Spatial Data의 경우 JPA로 불러오는데에 있어 문제가 발생해 long 타입 데이터로 저장하고 불러오기로 함 -> 해당 이슈는 추후 수정할 예정 

### 참고자료

[How to read geography values using hibernate?](https://stackoverflow.com/questions/57309861/how-to-read-geography-values-using-hibernate)

[Overview | Hibernate Spatial](http://www.hibernatespatial.org/)

[JPA를 이용해서 RDB에 공간정보 저장하기](https://semtax.tistory.com/91)

https://stackoverflow.com/questions/61098875/specification-predicate-for-hibernate-spatial-to-filter-an-entity-whether-it-is

[How to read geography values using hibernate?](https://stackoverflow.com/questions/57309861/how-to-read-geography-values-using-hibernate)

**Comment by Queue-ri** [comment]
long 타입은 정수형이라서 대신 `BigDecimal`은 어떠신지요? 그리고 spatial 오류나는 부분은 별도 이슈로 작성해주시면 이번 주에 확인해보겠습니다.

**Comment by tlsdhsdb** [comment]
BigDecimal 을 이용하여 테이블 새로 작성하였습니다 #14 

> long 타입은 정수형이라서 대신 `BigDecimal`은 어떠신지요? 그리고 spatial 오류나는 부분은 별도 이슈로 작성해주시면 이번 주에 확인해보겠습니다.
